config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'
  # Defines the root path route ("/")
  get '/users', to: 'users#index'

  # root "articles#index"
  get '/users/:id', to: 'users#show', as: 'user'

  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts', to: 'posts#create', as: 'user_posts_create'


  get '/users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'user_post_comments'


  post '/user/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'user_post_likes'
  get '/user/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/user/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  validates :text, presence: true

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :content, presence: true
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  # Public Methods
  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.update(post_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Personalized method
  def three_most_recent_posts
    posts.includes(:comments).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.first
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_user_and_post

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  private

  def find_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    @like = Like.new(user: current_user, post: @post)

    if @like.save
      flash.now[:notice] = 'Liked the post!'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:alert] = 'Failed to like the post!'
    end
  end

  private

  def find_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user

  def index
    @posts = @user.posts.includes(:comments, :likes).page(params[:page]).per(3)
  end

  def create
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'Post creation failed!'
      render :new
    end
  end

  def show
    @post = @user.posts.find(params[:id])
    @next_post = @user.posts.where('id > ?', @post.id).first
    @prev_post = @user.posts.where('id < ?', @post.id).last
  end

  def new
    @post = @user.posts.build
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @three_most_recent_posts = @user.posts.order(created_at: :desc).limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h2>New Comment</h2>
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [@user, @post, Comment.new], url: user_post_comments_path(@user, @post), class: 'comment-form') do |form| %>
  <div class="field">
    <%= form.label :text, "Comment" %>
    <%= form.text_area :text, rows: 4 %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Comment', class: 'button' %>
  </div>
<% end %>

<%= link_to 'Back', user_post_path(@user, @post), class: 'button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="container center">
    <%= yield %>
  </body>
</html>

app/views/likes/_likes_count.html.erb
<span class="span-post" data-target="likes_count">Likes: <%= post.likes.count %></span>

app/views/likes/create.js.erb
<%= turbo_stream.replace(
  @post, 
  partial: "likes_count",
  locals: { post: @post }
) %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<div>
  <div class="user-card flex">
    <div class="user-image border">
      <img src="<%= @user.photo %>" alt="<%= @user.name %>'s photo" width="100%" heigth="100%">
    </div>
    <div class="user-info border">
      <h2><%= @user.name %></h2>
      <p class="posts-number">Number of posts: <%= @user.posts.count %></p>
    </div>
  </div>
</div>

<div>
  <%= link_to 'New Post', new_user_post_path(@user), class: 'button' %>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <div id="post-<%= post.id %>" class="user-card left">
        <h3 data-id="<%= post.id %>"><%= link_to post.title, user_post_path(@user, post) %></h3>

          <br>
          <p><%= post.content %></p>
          <div class="right">
            <span class="span-post">Comments: <%= post.comments.count %></span>
            <span class="span-post" data-target="likes_count">Likes: <%= post.likes.count %></span>

          </div>
        </div>
        <div id="comments-for-post-<%= post.id %>" class="user-card left">
  <ul>
    <h5>All the Comments:</h5>
    <br>
    <% post.five_most_recent_comments.each do |comment| %>
    <li><%= comment.author.name %>: <%= comment.text %></li>
    <% end %>
  </ul>
</div>
      </li>
    <% end %>
  </ul>
</div>

<%= paginate @posts, param_name: 'page', class: 'button' %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [@user, @post], url: user_posts_create_path(@user), class: 'post-form') do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post', class: 'button' %>
  </div>
<% end %>

<%= link_to 'Back', user_posts_path(@user), class: 'button' %>

app/views/posts/show.html.erb
<h2>Total Comments</h2>
<div>
  <div class="user-card left">
    <h3><%= @post.title %> by <%= @user.name %></h3>
    <div class="right">
      <span class="span-post">Comments: <%= @post.comments.count %></span>
      <span class="span-post" data-target="likes_count">Likes: <%= @post.likes.count %></span>
      <%= button_to "Like", user_post_likes_path(@user, @post), method: :post, class: "button", remote: true %>
    </div>
    <br>
    <p><%= @post.content %></p>
  </div>
  <div class="user-card left">
    <ul>
      <h5>All the Comments:</h5>
      <br>
      <% @post.comments.each do |comment| %>
        <li><%= comment.author.name %>: <%= comment.text %></li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to 'New Comment', new_user_post_comment_path(@user, @post), class: 'button top' %>

<% if @prev_post.present? %>
  <%= button_to "Previous Post", user_post_path(@user, @prev_post), method: :get, class: "button top" %>
<% end %>

<% if @next_post.present? %>
  <%= button_to "Next Post", user_post_path(@user, @next_post), method: :get, class: "button top" %>
<% end %>

app/views/users/index.html.erb
<h1 class="index-title">All Users</h1>
<ul class="user-list">
  <% @users.each do |user| %>
    <li class="user-card flex" id="user-card-<%= user.id %>">
      <div class="user-image border">
        <img src="<%= user.photo %>" alt="<%= user.name %>'s photo" width="100% heigth="100%">
      </div>
      <div class="user-info border">
        <h2><%= link_to user.name, user_path(user) %></h2>
        <p class="posts-number">Number of posts: <%= user.posts.count %></p>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>User Information</h1>
<div class="user-card flex">
  <div class="user-image border">
    <img src="<%= @user.photo %>" alt="<%= @user.name %>'s photo" width="100%" height="100%">
  </div>
  <div class="user-info border">
    <h2><%= @user.name %></h2>
    <p class="posts-number">Number of posts: <%= @user.posts.count %></p>
  </div>
</div>
<div class="user-card left">
  <h3>Bio:</h3>
  <br>
  <p><%= @user.bio %></p>
</div>
<div>
  <ul>
    <% @user.three_most_recent_posts.each do |post| %>
      <li class="user-card left">
        <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
        <br>
        <p><%= post.content %></p>
        <div class="right">
          <span class="span-post">Comments: <%= post.comments.count %></span>
          <span class="span-post" data-target="likes_count">Likes: <%= post.likes.count %></span>
        </div>
      </li>
    <% end %>
  </ul>
  <%= button_to "See All Posts", user_posts_path(@user), method: :get, class: "button" %>
</div>